@urlApi = http://localhost:3000

### Get all posts
GET {{urlApi}}/api/posts

### Create post
POST  {{urlApi}}/api/posts
Content-Type: application/json

### Update post
PUT {{urlApi}}/api/posts/:id
Content-Type: application/json

### Delete post
DELETE  {{urlApi}}/api/posts/:id