### Get all posts
GET http://localhost:5000/api/posts

### Create post
POST http://localhost:5000/api/posts
Content-Type: application/json

{
    "title": "Septimo Post",
    "content": "La Septima descripcion de prueba",
    "imgUrl": "https://www.dzoom.org.es/wp-content/uploads/2021/09/nocturnas-con-luna-06-734x489.jpg"
}


### Update post
PUT http://localhost:5000/api/posts/1
Content-Type: application/json

{
    "title": "Titulo actualizado",
    "content": "Actualizamos si middlewares y validaciones funcionan",
    "imgUrl": "https://google.com"
}


### Delete post
DELETE http://localhost:5000/api/posts/6